# Generated by Django 4.2.4 on 2023-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_advetisements", "0002_advertisement_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                default="", upload_to="advertisements/", verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
    ]
